import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "MonaspiceKr NF"
style = "Bold"

[font.bold_italic]
family = "MonaspiceKr NF"
style = "Bold Italic"

[font.italic]
family = "MonaspiceKr NF"
style = "Italic"

[font.normal]
family = "MonaspiceKr NF"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "T"
mods = "Command"

[shell]
program = "/opt/homebrew/bin/tmux"

[window]
opacity = 0.98
option_as_alt = "OnlyLeft"

[window.padding]
x = 7
y = 5
